Let build-docs work with plain POSIX shell

diff --git a/scripts/build-docs b/scripts/build-docs
--- a/scripts/build-docs
+++ b/scripts/build-docs
@@ -1,4 +1,4 @@
-#!/usr/bin/env bash
+#!/bin/sh
 #
 # Copyright 2016 - 2018  Ternaris.
 # SPDX-License-Identifier: AGPL-3.0-only
@@ -7,12 +7,12 @@ set -e
 
 cd "$(dirname "$(realpath "$0")")"/../docs
 
-sphinx-build --help &>/dev/null || (
-    echo "ERROR: sphinx-build is not available, have you activate the virtualenv?"
+sphinx-build --help >/dev/null 2>&1 || (
+    echo "ERROR: sphinx-build is not available, have you activated the virtualenv?"
     exit 1
 )
-marv --help &>/dev/null || (
-    echo "ERROR: marv is not available, have you activate the virtualenv?"
+marv --help >/dev/null 2>&1 || (
+    echo "ERROR: marv is not available, have you activated the virtualenv?"
     exit 1
 )
 
@@ -20,4 +20,3 @@ make clean
 make html
 rm -rf ../code/marv-robotics/marv_robotics/docs
 cp -a ./_build/html ../code/marv-robotics/marv_robotics/docs
-
